version: "3"

networks:
  sentinel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.126.0.0/16
          gateway: 172.126.0.254

services:
  master-node:
    # image: redis:alpine
    image: redis
    command:
      - redis-server
      - --requirepass
      - redis_pwd
      - --masterauth
      - redis_pwd
    ports:
      - 6380:6379
    networks:
      sentinel-network:
        ipv4_address: 172.126.0.1


  slave-node1:
    # image: redis:alpine
    image: redis
    ports:
      - 6381:6379
    command: redis-server --slaveof master-node 6379 --requirepass redis_pwd --masterauth redis_pwd
    networks:
      sentinel-network:
        ipv4_address: 172.126.0.2

  slave-node2:
    # image: redis:alpine
    image: redis
    ports:
      - 6382:6379
    command: redis-server --slaveof master-node 6379 --requirepass redis_pwd --masterauth redis_pwd
    networks:
      sentinel-network:
        ipv4_address: 172.126.0.3

