version: "3"

services:
  sentinel-1:
    # image: redis:alpine
    image: redis
    ports:
      - 26379:26379
    command:
      - redis-sentinel
      - /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./etc/sentinel-1:/usr/local/etc/redis
    networks:
      default:
        ipv4_address: 172.126.0.4


  sentinel-2:
    # image: redis:alpine
    image: redis
    ports:
      - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./etc/sentinel-2:/usr/local/etc/redis
    networks:
      default:
        ipv4_address: 172.126.0.5


  sentinel-3:
    # image: redis:alpine
    image: redis
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./etc/sentinel-3:/usr/local/etc/redis
    networks:
      default:
        ipv4_address: 172.126.0.6


networks:
  # 和 redis 集群放在同一个网络
  default:
    external:
      name: redis_sentinel-network
