version: "2"
services:
  kafka-manager:
    image: sheepkiller/kafka-manager
    restart: always
    container_name: kafa-manager
    hostname: kafka-manager
    ports:
      - "9002:9000"
    external_links: # 连接本compose文件以外的container
      - broker1
      - broker2
      - broker3
      - zoo1
      - zoo2
      - zoo3
    environment:
      ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_BROKERS: broker1:9091,broker2:9092,broker3:9093
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
networks:
  # 注意配置和 zookeeper 集群在同一个网络才能通过服务名访问到 zookeeper 容器
  default:
    external:
      name: zookeeper_cluster_default
